// jtag_source.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module jtag_source (
		output wire [1:0] source  // sources.source, Source ports drive selected signals
	);

	altsource_probe_top #(
		.sld_auto_instance_index ("YES"),
		.sld_instance_index      (0),
		.instance_id             ("NONE"),
		.probe_width             (0),
		.source_width            (2),
		.source_initial_value    ("0"),
		.enable_metastability    ("NO")
	) in_system_sources_probes_0 (
		.source     (source), //  output,  width = 2, sources.source
		.source_clk (1'b0),   // (terminated),                     
		.source_ena (1'b1)    // (terminated),                     
	);

endmodule
